Silence warning in QtNetwork build
qnetworkconfigmanager.cpp:63:9: error: unused variable ‘shutdown’ [-Werror=unused-variable]

This warning was introduced by f273d6fbc02055ff3999adc0df76360ca0670435

Change-Id: Ied650a4d94d18495684a8f08ab5f2cd628026fb7
Reviewed-by: Jonas Gastal <gastal@intel.com>
Reviewed-by: Peter Hartmann <phartmann@blackberry.com>

cregit: 2cb5f1957ac709d27acbbdb49be8615670682212 https://github.com/qt/qtbase/commit/2cb5f1957ac709d27acbbdb49be8615670682212