qdrawhelper.cpp: Fix constexpr build with MSVC 2015 Update 1
error C2397: conversion from 'uint' to 'uchar' requires a narrowing conversion

Change-Id: Ic1b9e0a78b2faa5a0ae4e6de33ab2ee4b654af5f
Reviewed-by: Olivier Goffart (Woboq GmbH) <ogoffart@woboq.com>

cregit: 1378e7af1de3c0133e277ec3832ccd72e7286e67 https://github.com/qt/qtbase/commit/1378e7af1de3c0133e277ec3832ccd72e7286e67