Remove unused private fields in a class used for anti-flicker workaround
qwizard.cpp:510:14: error: private field 'wizard' is not used [-Werror,-Wunused-private-field]
qwizard.cpp:511:21: error: private field 'wizardPrivate' is not used [-Werror,-Wunused-private-field]

Field "wizard" was really unused, in all platforms, so simply remove
it. The field "wizardPrivate" is used when the Windows Vista style is
enabled.

Change-Id: I1ce254f484b613655bff7f6c3ee8e04479960d7c
Reviewed-by: Friedemann Kleint <Friedemann.Kleint@digia.com>
Reviewed-by: Jan Arve Sæther <jan-arve.saether@digia.com>

cregit: 336eac089623be3c824b19a1161d19906ae6125f https://github.com/qt/qtbase/commit/336eac089623be3c824b19a1161d19906ae6125f