qfactoryloader: static qt compile fix
statically linked qt does not compile, as versionKeyLiteral() is unused,
causing clang to complain:
error: unused function 'versionKeyLiteral' [-Werror,-Wunused-function]

Change-Id: I6a233081e7c58fce75ece82616f937f29a23a81b
Reviewed-by: Tor Arne Vestbø <tor.arne.vestbo@theqtcompany.com>

cregit: 970f44bf484fba6ee8b6976768996e0b3dc8b2df https://github.com/qt/qtbase/commit/970f44bf484fba6ee8b6976768996e0b3dc8b2df