Attempt to fix intel compiler build error.
qtbase/include/QtCore/../../src/corelib/kernel/qobjectdefs_impl.h(625): error #68: integer conversion resulted in a change of sign

Task-number: QTBUG-39678
Change-Id: Ifb175bdcad820aa58cc0a1bcf6985a164376baf5
Reviewed-by: Olivier Goffart <ogoffart@woboq.com>
Reviewed-by: Thiago Macieira <thiago.macieira@intel.com>

cregit: 1a034ac218ee912b2f565a2fbafd7eb53ad6a3bd https://github.com/qt/qtbase/commit/1a034ac218ee912b2f565a2fbafd7eb53ad6a3bd