tst_QSslError: cleanup unused functions
Change-Id: I4db7399e533805e1dddaa76d5a609d2006a97da6
Reviewed-by: Giuseppe D'Angelo <giuseppe.dangelo@kdab.com>

cregit: 10e5bcf9d0428992c29d8822671933fa49f0ae37 https://github.com/qt/qtbase/commit/10e5bcf9d0428992c29d8822671933fa49f0ae37