Revert "Move the glxfbconfig configtest to qpa and rename it to glx"
This reverts commit a2d3b7c99165cb5c4be6f0dd83a967e1119cf732. That
commit broke -opengl es2 builds on Linux desktops (when GLX is
available).

/usr/include/GL/gl.h:162:17: error: conflicting declaration ‘typedef double GLdouble’
qopengl.h:97:17: error: ‘GLdouble’ has a previous declaration as ‘typedef GLfloat GLdouble’

Change-Id: Id5f48c05803be1a8c03eeffca139b80e9a85a0eb
Reviewed-by: Thiago Macieira <thiago.macieira@intel.com>

cregit: 8be546d107ac69bc48ec278396e9c3f63470fd0d https://github.com/qt/qtbase/commit/8be546d107ac69bc48ec278396e9c3f63470fd0d