Revert "Add support for same-file intrinsics with Clang 3.7"
This reverts commit 39c2b8c5c12dfb8560fa04ce346a129adb223e29. The
feature is not working:

$ clang -c -o /dev/null -msse2 -include tmmintrin.h -xc /dev/null
In file included from <built-in>:316:
In file included from <command line>:1:
/home/thiago/clang3.7/bin/../lib/clang/3.7.0/include/tmmintrin.h:28:2: error: "SSSE3 instruction set not enabled"

For reference:

$ icpc -c -o /dev/null -msse2 -include tmmintrin.h -xc /dev/null; echo $?
0
$ gcc -c -o /dev/null -msse2 -include tmmintrin.h -xc /dev/null; echo $?
0

Change-Id: I42e7ef1a481840699a8dffff140844cb8872ed6e
Reviewed-by: Sérgio Martins <sergio.martins@kdab.com>

cregit: e9365c2c2fecbc779c44456fb1c946905a670684 https://github.com/qt/qtbase/commit/e9365c2c2fecbc779c44456fb1c946905a670684