Silence warning about unused parameter
Happened on an iOS build

io/qlockfile_unix.cpp:217:51: error: unused parameter 'pid' [-Werror,-
Wunused-parameter]

Change-Id: Id3d5c7bf4d4c45069621ffff13f7f7a30728c071
Reviewed-by: Jake Petroules <jake.petroules@petroules.com>

cregit: 2faa5f9d09d1f56f3dd2d94399293752e78ec498 https://github.com/qt/qtbase/commit/2faa5f9d09d1f56f3dd2d94399293752e78ec498