QIconvCodec: fix compilation when NO_BOM is defined.
qiconvcodec.cpp:305:34: error: unused parameter 'cd' [-Werror,-Wunused-parameter]

Change-Id: I27eaacb532114dd188c4ffff13d330b64b4feaa6
Reviewed-by: Lars Knoll <lars.knoll@digia.com>

cregit: bc00e6da8477a5fc0e547733effef9db944f3eab https://github.com/qt/qtbase/commit/bc00e6da8477a5fc0e547733effef9db944f3eab