Fix undefined behavior found by GCC 5
GCC said:
qtldurl.cpp:51:50: error: loop exit may only be reached after undefined behavior [-Werror=aggressive-loop-optimizations]
qtldurl.cpp:51:48: note: possible undefined statement is here
     while (tldIndices[index] >= tldChunks[chunk] && chunk < tldChunkCount) {
                                                ^

That's because we check whether chunk is still valid (less than
tldChunkCount) after we've dereferenced tldChunks[chunk]. That is, we've
already read tldChunk[2].

Change-Id: I79b6a1ea9a2454813d6cce7596fc2bb6d972d097
Reviewed-by: David Faure <david.faure@kdab.com>

cregit: cd407e1bc616bb98eef83d2b5c64513507ed1ef5 https://github.com/qt/qtbase/commit/cd407e1bc616bb98eef83d2b5c64513507ed1ef5