QDBusError: declare as shared-come-Qt6
Requires adding member-swap and (at least in my copy) move operations.

Change-Id: I4284484b1f520eb2d9036b993a5b5b70aaea0af9
Reviewed-by: Thiago Macieira <thiago.macieira@intel.com>

cregit: 84769bbbce2f175a48c66954cb863e9c0855394b https://github.com/qt/qtbase/commit/84769bbbce2f175a48c66954cb863e9c0855394b