Fix change-of-sign warning found by ICC
qstring.cpp(3896): error #68: integer conversion resulted in a change of sign

The line before also had 0x8000, but since there was no addition,
0x8000 was a literal converted to short. However, 0xff + 0x8000 is an
int, and 0x80ff is positive, while short(0x80ff) is negative.

Change-Id: I445ff401d817b643479e54320525890ce12bbfe5
Reviewed-by: Olivier Goffart <ogoffart@woboq.com>
Reviewed-by: Robin Burchell <robin+qt@viroteck.net>
Reviewed-by: Frederik Gladhorn <frederik.gladhorn@digia.com>

cregit: fc4d45d97d7a971aa179f73d41455544b400e960 https://github.com/qt/qtbase/commit/fc4d45d97d7a971aa179f73d41455544b400e960