Remove unused private member (fixes compilation with Clang 3.4)
qkmsscreen.h:114:18: error: private field 'm_refreshTime' is not used

Change-Id: Id9c802c5c3ae2ffdf61238f083bfe875e7b613a8
Reviewed-by: Laszlo Agocs <laszlo.agocs@digia.com>

cregit: d084590d2bfbd60a58aceee7228eddca608f1893 https://github.com/qt/qtbase/commit/d084590d2bfbd60a58aceee7228eddca608f1893