Introduce Q_STATIC_ASSERT
Example of message of failed assert (gcc 4.6, file tst_qglobal.cpp:300):
tst_qglobal.cpp:300:92: error: invalid application of ‘sizeof’
to incomplete type ‘QStaticAssertFailure<false>’

Change-Id: Ic1798094f718eaad388d754034115aafbbb6bd5e
Reviewed-by: João Abecasis <joao.abecasis@nokia.com>

cregit: 663cd1771883e1e7ac9c1a0dc8b797601b59ba17 https://github.com/qt/qtbase/commit/663cd1771883e1e7ac9c1a0dc8b797601b59ba17