Fix win32-g++ build due to -Werror
qwindowsprintdevice.cpp:182:85: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
         && DeviceCapabilities((LPWSTR)m_id.utf16(), NULL, DC_PAPERSIZE, NULL, NULL) == paperCount

MinGW DeviceCapabilities is returning an int, although microsoft documents it as returning DWORD.

Change-Id: I3acd76dde0b8b83f8a785ec84e3413115c847cb2
Reviewed-by: Friedemann Kleint <Friedemann.Kleint@theqtcompany.com>
Reviewed-by: Thiago Macieira <thiago.macieira@intel.com>

cregit: 9a0c4fc479b2f46f569890a2821e56b2943efac5 https://github.com/qt/qtbase/commit/9a0c4fc479b2f46f569890a2821e56b2943efac5