test: tst_qhostinfo requires \`private_tests' set
Otherwise you get:

  undefined reference to \`qt_qhostinfo_clear_cache()'

Change-Id: I32313f290b9e4236440ae01afe12285d4539be60
Reviewed-by: Peter Hartmann <phartmann@blackberry.com>

cregit: f15d73058903eee77daa0a3f6deb8554aa01ea93 https://github.com/qt/qtbase/commit/f15d73058903eee77daa0a3f6deb8554aa01ea93