Fix warning about unused variable
qeglfshooks.h:77:21: error: 'hooks' defined but not used [-Werror=unused-variable]

Defining a static variable in a header file is a terrible idea. But if
I remove it, other code breaks and I don't have the time to fix them
all.

Change-Id: I4f94cbc7f0790df91853662749701e8fb11c2347
Reviewed-by: Samuel Rødal <samuel.rodal@digia.com>

cregit: afa57146cb519f27d816a295dadb2f0e71733f4b https://github.com/qt/qtbase/commit/afa57146cb519f27d816a295dadb2f0e71733f4b