Fix compilation with GCC 4.9.2 and up in debug mode
Somehow the const int is no longer understood to be an immediate. GCC
4.8 still compiles this fine.

qstring.cpp:316:34: error: the fifth argument must be an 8-bit immediate

Change-Id: Ib056b47dde3341ef9a52ffff13ef24d541833abc
Reviewed-by: Marc Mutz <marc.mutz@kdab.com>
Reviewed-by: Olivier Goffart (Woboq GmbH) <ogoffart@woboq.com>

cregit: c84625f0d565d12038c72528d1af9bee1a7100bc https://github.com/qt/qtbase/commit/c84625f0d565d12038c72528d1af9bee1a7100bc