fix build on symbian
Error:  #793: explicit specialization of class "QTypeInfo<QProcessEnvironmentPrivate::Key>" must precede its first use

just un-nest QProcessEnvironmentPrivate::{Key,Value}

Reviewed-by: thiago
(cherry picked from commit 167044693cc1d16684a5732b05e3926d0af61960)

cregit: 95e57339a9c02943edbd0cc7d4470a2ed044a7c2 https://github.com/qt/qtbase/commit/95e57339a9c02943edbd0cc7d4470a2ed044a7c2