Fix warning caused by warning fix
qevent.h:865:36: error: unknown warning group '-Wunused-private-field', ignored [-Werror,-Wunknown-pragmas]

Instead, just use Q_UNUSED() like I've done for the other unused
members.

Change-Id: I3adeb06937cee8b8ac24a1d5081be03931ac98b7
Reviewed-by: Stephen Kelly <stephen.kelly@kdab.com>

cregit: 4bc450408c917381b486c03a0462b3c7b88abe1e https://github.com/qt/qtbase/commit/4bc450408c917381b486c03a0462b3c7b88abe1e